/**
 * Prototype File Service
 *
 * Handles multi-file prototypes generated by the tool-based approach.
 * Manages fetching, storing, and navigating prototype bundles.
 */

import { supabase, isSupabaseConfigured } from './supabase';
import type {
  ModificationSpec,
  PrototypeBundle,
  PrototypeFile,
  Route,
  PrototypeFileType,
} from '@/types/toolSchema';

// =============================================================================
// Types
// =============================================================================

export interface PrototypeFileRecord {
  id: string;
  session_id: string;
  variant_index: number;
  filename: string;
  content: string;
  file_type: PrototypeFileType;
  is_entry: boolean;
  screen_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface StoredPrototypeBundle {
  sessionId: string;
  variantIndex: number;
  files: PrototypeFile[];
  entryPoint: string;
  spec: ModificationSpec | null;
  createdAt: string;
}

// =============================================================================
// Fetch Operations
// =============================================================================

/**
 * Get all files for a prototype bundle
 */
export async function getPrototypeBundle(
  sessionId: string,
  variantIndex: number
): Promise<StoredPrototypeBundle | null> {
  if (!isSupabaseConfigured()) {
    console.warn('[PrototypeFileService] Supabase not configured');
    return null;
  }

  const { data, error } = await supabase
    .from('prototype_files')
    .select('*')
    .eq('session_id', sessionId)
    .eq('variant_index', variantIndex)
    .order('filename', { ascending: true });

  if (error) {
    console.error('[PrototypeFileService] Error fetching prototype files:', error);
    return null;
  }

  if (!data || data.length === 0) {
    return null;
  }

  const records = data as PrototypeFileRecord[];
  const files: PrototypeFile[] = records.map(r => ({
    filename: r.filename,
    content: r.content,
    type: r.file_type,
    isEntry: r.is_entry,
    screenId: r.screen_id || undefined,
  }));

  // Find entry point
  const entryFile = files.find(f => f.isEntry);
  const entryPoint = entryFile?.filename || 'main.html';

  // Find spec file if exists
  const specFile = files.find(f => f.filename === '_spec.json');
  let spec: ModificationSpec | null = null;
  if (specFile) {
    try {
      spec = JSON.parse(specFile.content);
    } catch {
      console.warn('[PrototypeFileService] Failed to parse spec file');
    }
  }

  return {
    sessionId,
    variantIndex,
    files: files.filter(f => f.filename !== '_spec.json'),
    entryPoint,
    spec,
    createdAt: records[0]?.created_at || new Date().toISOString(),
  };
}

/**
 * Get a single file from a prototype
 */
export async function getPrototypeFile(
  sessionId: string,
  variantIndex: number,
  filename: string
): Promise<PrototypeFile | null> {
  if (!isSupabaseConfigured()) {
    return null;
  }

  const { data, error } = await supabase
    .from('prototype_files')
    .select('*')
    .eq('session_id', sessionId)
    .eq('variant_index', variantIndex)
    .eq('filename', filename)
    .single();

  if (error || !data) {
    return null;
  }

  const record = data as PrototypeFileRecord;
  return {
    filename: record.filename,
    content: record.content,
    type: record.file_type,
    isEntry: record.is_entry,
    screenId: record.screen_id || undefined,
  };
}

/**
 * Get modification spec for a prototype
 */
export async function getPrototypeSpec(
  sessionId: string,
  variantIndex: number
): Promise<ModificationSpec | null> {
  // Try from database first
  const specFile = await getPrototypeFile(sessionId, variantIndex, '_spec.json');
  if (specFile) {
    try {
      return JSON.parse(specFile.content);
    } catch {
      console.warn('[PrototypeFileService] Failed to parse spec from database');
    }
  }

  // Try from storage
  if (!isSupabaseConfigured()) {
    return null;
  }

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return null;
  }

  const specPath = `${user.id}/${sessionId}/variant_${variantIndex}_spec.json`;
  const { data, error } = await supabase.storage
    .from('vibe-files')
    .download(specPath);

  if (error || !data) {
    return null;
  }

  try {
    const text = await data.text();
    return JSON.parse(text);
  } catch {
    console.warn('[PrototypeFileService] Failed to parse spec from storage');
    return null;
  }
}

// =============================================================================
// Store Operations
// =============================================================================

/**
 * Store all files for a prototype bundle
 */
export async function storePrototypeBundle(
  sessionId: string,
  variantIndex: number,
  bundle: PrototypeBundle
): Promise<boolean> {
  if (!isSupabaseConfigured()) {
    return false;
  }

  const records: Omit<PrototypeFileRecord, 'id' | 'created_at' | 'updated_at'>[] = [];

  // Add all files
  for (const [filename, content] of bundle.files) {
    const type = getFileType(filename);
    const isEntry = filename === bundle.entryPoint;
    const screenId = getScreenIdFromFilename(filename, bundle.manifest.screens);

    records.push({
      session_id: sessionId,
      variant_index: variantIndex,
      filename,
      content,
      file_type: type,
      is_entry: isEntry,
      screen_id: screenId,
    });
  }

  // Add spec file
  records.push({
    session_id: sessionId,
    variant_index: variantIndex,
    filename: '_spec.json',
    content: JSON.stringify(bundle.spec, null, 2),
    file_type: 'json',
    is_entry: false,
    screen_id: null,
  });

  // Upsert all records
  const { error } = await supabase
    .from('prototype_files')
    .upsert(records, {
      onConflict: 'session_id,variant_index,filename',
    });

  if (error) {
    console.error('[PrototypeFileService] Error storing prototype files:', error);
    return false;
  }

  return true;
}

/**
 * Store a single prototype file
 */
export async function storePrototypeFile(
  sessionId: string,
  variantIndex: number,
  file: PrototypeFile
): Promise<boolean> {
  if (!isSupabaseConfigured()) {
    return false;
  }

  const { error } = await supabase
    .from('prototype_files')
    .upsert({
      session_id: sessionId,
      variant_index: variantIndex,
      filename: file.filename,
      content: file.content,
      file_type: file.type,
      is_entry: file.isEntry || false,
      screen_id: file.screenId || null,
    }, {
      onConflict: 'session_id,variant_index,filename',
    });

  if (error) {
    console.error('[PrototypeFileService] Error storing prototype file:', error);
    return false;
  }

  return true;
}

/**
 * Update modification spec and regenerate files
 */
export async function updatePrototypeSpec(
  sessionId: string,
  variantIndex: number,
  spec: ModificationSpec
): Promise<boolean> {
  // Store the updated spec
  const specStored = await storePrototypeFile(sessionId, variantIndex, {
    filename: '_spec.json',
    content: JSON.stringify(spec, null, 2),
    type: 'json',
  });

  if (!specStored) {
    return false;
  }

  // TODO: Trigger regeneration of HTML files from the spec
  // This would call the DOM modifier to apply the spec to source HTML

  return true;
}

// =============================================================================
// Delete Operations
// =============================================================================

/**
 * Delete all files for a prototype
 */
export async function deletePrototypeBundle(
  sessionId: string,
  variantIndex: number
): Promise<boolean> {
  if (!isSupabaseConfigured()) {
    return false;
  }

  const { error } = await supabase
    .from('prototype_files')
    .delete()
    .eq('session_id', sessionId)
    .eq('variant_index', variantIndex);

  if (error) {
    console.error('[PrototypeFileService] Error deleting prototype files:', error);
    return false;
  }

  return true;
}

// =============================================================================
// List Operations
// =============================================================================

/**
 * List all screens in a prototype
 */
export async function listPrototypeScreens(
  sessionId: string,
  variantIndex: number
): Promise<string[]> {
  if (!isSupabaseConfigured()) {
    return [];
  }

  const { data, error } = await supabase
    .from('prototype_files')
    .select('screen_id')
    .eq('session_id', sessionId)
    .eq('variant_index', variantIndex)
    .not('screen_id', 'is', null);

  if (error) {
    console.error('[PrototypeFileService] Error listing screens:', error);
    return [];
  }

  const screenIds = new Set<string>();
  for (const record of data || []) {
    if (record.screen_id) {
      screenIds.add(record.screen_id);
    }
  }

  return Array.from(screenIds);
}

/**
 * Check if a prototype uses tool mode (has spec)
 */
export async function isToolModePrototype(
  sessionId: string,
  variantIndex: number
): Promise<boolean> {
  const spec = await getPrototypeSpec(sessionId, variantIndex);
  return spec !== null;
}

// =============================================================================
// Navigation
// =============================================================================

/**
 * Get navigation routes for a prototype
 */
export async function getPrototypeRoutes(
  sessionId: string,
  variantIndex: number
): Promise<Route[]> {
  const spec = await getPrototypeSpec(sessionId, variantIndex);
  return spec?.navigation?.routes || [];
}

/**
 * Get default screen for a prototype
 */
export async function getDefaultScreen(
  sessionId: string,
  variantIndex: number
): Promise<string> {
  const spec = await getPrototypeSpec(sessionId, variantIndex);
  return spec?.navigation?.defaultScreen || 'main';
}

// =============================================================================
// Helpers
// =============================================================================

/**
 * Get file type from filename extension
 */
function getFileType(filename: string): PrototypeFileType {
  if (filename.endsWith('.html')) return 'html';
  if (filename.endsWith('.css')) return 'css';
  if (filename.endsWith('.js')) return 'js';
  if (filename.endsWith('.json')) return 'json';
  return 'html'; // Default
}

/**
 * Extract screen ID from filename
 */
function getScreenIdFromFilename(
  filename: string,
  screens: string[]
): string | null {
  // Remove extension
  const name = filename.replace(/\.(html|htm)$/, '');

  // Check if it matches a known screen
  if (screens.includes(name)) {
    return name;
  }

  return null;
}

/**
 * Build a combined HTML with all screens embedded (for single-file preview)
 */
export function buildCombinedHTML(bundle: StoredPrototypeBundle): string {
  const htmlFiles = bundle.files.filter(f => f.type === 'html');

  if (htmlFiles.length === 1) {
    return htmlFiles[0].content;
  }

  // For multi-screen prototypes, return the entry point
  // The navigation script will handle screen switching
  const entryFile = bundle.files.find(f => f.filename === bundle.entryPoint);
  return entryFile?.content || htmlFiles[0]?.content || '';
}
